### ISSUE TITLE
1.8.8 fails to launch on Prism Launcher

### ISSUE THREAD

**Issue by splice11** [Sol-Client/Installer#3]
![image](https://user-images.githubusercontent.com/92755960/197327924-88969e9e-f30b-4a44-8cff-f88c3f4f4913.png)
![image](https://user-images.githubusercontent.com/92755960/197327946-af11799f-5c92-4565-8298-ad0dd236d308.png)

**Comment by TheKodeToad** [comment]
This is already a known issue, and I'm trying to fix it.

**Comment by TheKodeToad** [comment]
This has now been fixed in [dev-6](https://github.com/Sol-Client/Installer/releases/tag/dev-6).
